Top course Olexandr Cherkasov
Genesis-Front-End-School/clean-code-principes-xtadeushx pull request #2
Opened 2023-04-14 08:53 UTC by xtadeushx

Please check my work.

2023-04-17 19:05 UTC, Diana064 approved these changes
Дуже гарно структурвані файли, мні подобається що немає зайвих коментів, все оформлено чітко, тільки для зручності додала одну правку.

2023-04-17 19:05 UTC, Diana064 commented on src/main.tsx
Тут я би радила зробити окремий файл, який називаеться глобальні стилі, де я б прописала глобальні стилі
 і прокинути їх пропсом, пришлю приклад файла. з глобальними стилями, це зручно тим, що змінюєш один колір і він. змінюється будь де.
 
`ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <BrowserRouter basename="/genesisTechTest">
      <ThemeProvider theme={theme}>
        <GlobalStyle />
        <App />
      </ThemeProvider>
    </BrowserRouter>
  </React.StrictMode>
);

`
`export const theme = {
  colors: {
    black: '#000',
    white: '#fff',
    subtitle: '#500805',
    title: '#000',
    border: '#A1D6E2',
    back: '#fff',
    backCourse: '#F1F1F2',
    mainText: '#896e69',
    peach: '#ffa577',
    text: '#313436',
  },
  space: [0, 2, 4, 8, 16, 32, 64, 128, 256],
  gap: [10, 15, 17, 20, 25, 30],

  fontSizes: {
    xs: '12px',
    s: '14px',
    m: '16px',
    l: '21px',
    xl: '32px',
  },
  fontWeights: {
    normal: 400,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  borders: {
    none: 'none',
    normal: '1px solid',
    big: '2px solid',
  },
  radii: {
    none: '0',
    sm: '4px',
    md: '8px',
    lg: '16px',
    round: '50%',
  },
};
`

2023-04-17 19:05 UTC, Diana064 commented on src/main.tsx
чогось код не підгрузив, тобто просто обгорнути App в компоннт і прокинути пропси, щоб стилізувати6 наприклад так 
 background-color: ${p => p.theme.colors.back};

2023-04-17 19:20 UTC, Diana064 commented on src/main.tsx
<img width="486" alt="Снимок экрана 2023-04-17 в 22 20 39" src="https://user-images.githubusercontent.com/98182589/232589363-67cd8515-0edd-4736-a2b9-f55d93c63db6.png">

2023-04-17 20:12 UTC, 37flwr commented on src/helpers/time/time-formate.helper.ts
> +  hours = +hours < 10 ? '0' + hours : hours;
На мій погляд, краще використовувати явне перетворення типів (parseInt, Number…), адже воно краще читається і в унарному + є певні виключення
Але в даному випадку дійсно це ні на що не вплине)

2023-04-17 20:13 UTC, 37flwr commented on src/components/courses/components/course-content/course-content.tsx
> +        {lessons &&
Можна замінити на lessons?.map(…)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
Тут трішки більше інформації про даний вираз

2023-04-18 06:40 UTC, xtadeushx commented on src/helpers/time/time-formate.helper.ts
> +  hours = +hours < 10 ? '0' + hours : hours;
змінив дякую

2023-04-18 06:40 UTC, xtadeushx commented on src/components/courses/components/course-content/course-content.tsx
> +        {lessons &&
змінив дякую

2023-04-18 06:43 UTC, xtadeushx commented on src/main.tsx
я використовую modules.css тому щоб імплентувати твої зауваження треба підключати зайву лібу styled-component or tailwind і це вплине на інші файли стилів. Дякую за твій коментар.

2023-04-19 13:43 UTC, olesmarola requested changes

2023-04-19 13:43 UTC, olesmarola commented on src/common/types/course.types.ts
> +export interface ICourse {
If you use the `I` prefix, use it for all interfaces, not only for one... Use another name for the interface if the Course already exists.

2023-04-19 13:43 UTC, olesmarola commented on src/components/app/App.tsx
> +  const { courses } = response;
Why do you need it?

2023-04-19 13:43 UTC, olesmarola commented on src/components/app/App.tsx
> +              courses={courses}
```suggestion
              courses={response.courses}
```

2023-04-19 13:43 UTC, olesmarola commented on src/components/common/button/button.tsx
> +  onClick,
```suggestion
```

2023-04-19 13:43 UTC, olesmarola commented on src/components/common/button/button.tsx
> +      onClick={onClick}
```suggestion
```

2023-04-19 13:43 UTC, olesmarola commented on src/components/common/button/types.ts
> +
You can store this type in the component type for better readability.

2023-04-19 13:43 UTC, olesmarola commented on src/components/common/footer/footer.module.scss
> +/* footer */
🧐

2023-04-19 13:43 UTC, olesmarola commented on src/components/common/footer/footer.module.scss
> +
Use nesting abilities provided by scss

2023-04-19 13:43 UTC, olesmarola commented on src/components/common/header/header.module.scss
> +.header__logo {
scss....

2023-04-19 13:43 UTC, olesmarola commented on src/components/common/loader/loader.tsx
> +  isOverflow ? (
Overflow of what?

2023-04-19 13:43 UTC, olesmarola commented on src/components/common/loader/types.ts
> +export type TSpinner = {
leave in the same file with component

2023-04-19 13:43 UTC, olesmarola commented on src/components/common/video/video.tsx
> +    }
Wrap functions with `useCallback`

2023-04-19 13:43 UTC, olesmarola commented on src/components/paginate/pagination.tsx
> +  const handlePageClick = (event: any) => {
Wrap with `useCallback`

2023-04-26 09:48 UTC, merged